version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`     
      - dotnet restore .\entityframeworkDotnetcore\entityframeworkDotnetcore\entityframeworkDotnetcore.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output .\entityframeworkDotnetcore\entityframeworkDotnetcore\entityframeworkDotnetcore.csproj
artifacts:
  files:
    - .\build_output