version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore  entityframeworkDotnetcore\entityframeworkDotnetcore\
  build:
    commands:
      - dotnet restore
      - dotnet build
artifacts:
  files:
    - .\bin\Debug\netcoreapp3.1\*